"""Static fallback lists used by update_universe.py when NSE downloads are unavailable."""

NSE_INDICES = [{'symbol': '^NSEI', 'company_name': 'Nifty 50', 'series': 'INDEX'},
 {'symbol': '^NSEBANK', 'company_name': 'Nifty Bank', 'series': 'INDEX'},
 {'symbol': '^NSMIDCP', 'company_name': 'Nifty Midcap 50', 'series': 'INDEX'},
 {'symbol': '^CNXSC', 'company_name': 'Nifty Smallcap 100', 'series': 'INDEX'},
 {'symbol': '^CRSLDX', 'company_name': 'Nifty 500', 'series': 'INDEX'},
 {'symbol': '^NIFMDCP100', 'company_name': 'Nifty Midcap 100', 'series': 'INDEX'},
 {'symbol': '^NIFSMCP250', 'company_name': 'Nifty Smallcap 250', 'series': 'INDEX'},
 {'symbol': '^NSE200', 'company_name': 'Nifty 200', 'series': 'INDEX'},
 {'symbol': '^NIFTY100', 'company_name': 'Nifty 100', 'series': 'INDEX'},
 {'symbol': '^CNXIT', 'company_name': 'Nifty IT', 'series': 'INDEX'},
 {'symbol': '^CNXFIN', 'company_name': 'Nifty Financial Services', 'series': 'INDEX'},
 {'symbol': '^CNXPHARMA', 'company_name': 'Nifty Pharma', 'series': 'INDEX'},
 {'symbol': '^CNXAUTO', 'company_name': 'Nifty Auto', 'series': 'INDEX'},
 {'symbol': '^CNXFMCG', 'company_name': 'Nifty FMCG', 'series': 'INDEX'},
 {'symbol': '^CNXENERGY', 'company_name': 'Nifty Energy', 'series': 'INDEX'},
 {'symbol': '^CNXREALTY', 'company_name': 'Nifty Realty', 'series': 'INDEX'},
 {'symbol': '^CNXMETAL', 'company_name': 'Nifty Metal', 'series': 'INDEX'},
 {'symbol': '^CNXMEDIA', 'company_name': 'Nifty Media', 'series': 'INDEX'},
 {'symbol': '^CNXINFRA', 'company_name': 'Nifty Infrastructure', 'series': 'INDEX'},
 {'symbol': '^CNXCMDT', 'company_name': 'Nifty Commodities', 'series': 'INDEX'},
 {'symbol': '^CNXPSUBANK', 'company_name': 'Nifty PSU Bank', 'series': 'INDEX'},
 {'symbol': '^CNXPSE', 'company_name': 'Nifty PSE', 'series': 'INDEX'},
 {'symbol': '^CNXMNC', 'company_name': 'Nifty MNC', 'series': 'INDEX'},
 {'symbol': '^NIFTYHEALTH', 'company_name': 'Nifty Healthcare', 'series': 'INDEX'},
 {'symbol': '^NIFTYOIL', 'company_name': 'Nifty Oil & Gas', 'series': 'INDEX'},
 {'symbol': '^CNXCONSUM', 'company_name': 'Nifty Consumer Durables', 'series': 'INDEX'},
 {'symbol': '^NIFTY50EQ', 'company_name': 'Nifty50 Equal Weight', 'series': 'INDEX'},
 {'symbol': '^NIFTYDIV', 'company_name': 'Nifty Dividend Opps 50', 'series': 'INDEX'},
 {'symbol': '^NIFTYALPHA', 'company_name': 'Nifty Alpha 50', 'series': 'INDEX'},
 {'symbol': '^NIFTYMICRO', 'company_name': 'Nifty Microcap 250', 'series': 'INDEX'}]

NSE_ETFS = [{'symbol': 'NIFTYBEES', 'company_name': 'Nippon India ETF Nifty BeES'},
 {'symbol': 'BANKBEES', 'company_name': 'Nippon India ETF Bank BeES'},
 {'symbol': 'JUNIORBEES', 'company_name': 'Nippon India ETF Junior BeES'},
 {'symbol': 'MIDCAPETF', 'company_name': 'DSP Nifty Midcap 50 ETF'},
 {'symbol': 'MOM100', 'company_name': 'Motilal Oswal Nifty Momentum 100 ETF'},
 {'symbol': 'QUAL30IETF', 'company_name': 'DSP Nifty50 Equal Weight ETF'},
 {'symbol': 'ITETF', 'company_name': 'Nippon India ETF Nifty IT'},
 {'symbol': 'PHARMABEES', 'company_name': 'Nippon India ETF Nifty Pharma BeES'},
 {'symbol': 'AUTOBEES', 'company_name': 'Nippon India ETF Nifty Auto'},
 {'symbol': 'INFRABEES', 'company_name': 'Nippon India ETF Nifty Infra BeES'},
 {'symbol': 'PSUBANKETF', 'company_name': 'Nippon India ETF PSU Bank BeES'},
 {'symbol': 'PVTBANKETF', 'company_name': 'Kotak Nifty Pvt Bank ETF'},
 {'symbol': 'NETFIT', 'company_name': 'Nippon India ETF Nifty Financial Services'},
 {'symbol': 'HEALTHCARE', 'company_name': 'HDFC Nifty Healthcare ETF'},
 {'symbol': 'METALIETF', 'company_name': 'Nippon India ETF Nifty Metal'},
 {'symbol': 'CONSUMBEES', 'company_name': 'Nippon India ETF Nifty FMCG BeES'},
 {'symbol': 'MOM50', 'company_name': 'Motilal Oswal Nifty Momentum 50 ETF'},
 {'symbol': 'ALPHA', 'company_name': 'Nifty Alpha Low Volatility 30 ETF'},
 {'symbol': 'LOWVOLIETF', 'company_name': 'DSP Nifty50 Value 20 ETF'},
 {'symbol': 'NV20IETF', 'company_name': 'Nippon India ETF Nifty50 Value 20'},
 {'symbol': 'GOLDBEES', 'company_name': 'Nippon India ETF Gold BeES'},
 {'symbol': 'GOLDSHARE', 'company_name': 'UTI Gold ETF'},
 {'symbol': 'HDFCGOLD', 'company_name': 'HDFC Gold ETF'},
 {'symbol': 'KOTAKGOLD', 'company_name': 'Kotak Gold ETF'},
 {'symbol': 'AXISGOLD', 'company_name': 'Axis Gold ETF'},
 {'symbol': 'SILVRETF', 'company_name': 'Nippon India ETF Silver BeES'},
 {'symbol': 'SILVERIETF', 'company_name': 'ICICI Pru Silver ETF'},
 {'symbol': 'LIQUIDBEES', 'company_name': 'Nippon India ETF Nifty 1D Rate Liquid BeES'},
 {'symbol': 'LIQUIDCASE', 'company_name': 'Mirae Asset Nifty 1D Rate Liquid ETF'},
 {'symbol': 'ICICILIQ', 'company_name': 'ICICI Pru Liquid ETF'},
 {'symbol': 'ABSLBANETF', 'company_name': 'Aditya Birla SL Nifty Bank ETF'},
 {'symbol': 'HDFCNIFBAN', 'company_name': 'HDFC Nifty Bank ETF'},
 {'symbol': 'SETFNIFBK', 'company_name': 'SBI ETF Nifty Bank'},
 {'symbol': 'SETFNIF50', 'company_name': 'SBI ETF Nifty 50'},
 {'symbol': 'SETFNIF100', 'company_name': 'SBI ETF Nifty 100'},
 {'symbol': 'ICICINIFTY', 'company_name': 'ICICI Pru Nifty 50 ETF'},
 {'symbol': 'ICICINF100', 'company_name': 'ICICI Pru Nifty 100 ETF'},
 {'symbol': 'HDFCNIFTY', 'company_name': 'HDFC Nifty 50 ETF'},
 {'symbol': 'HDFCNIF100', 'company_name': 'HDFC Nifty 100 ETF'},
 {'symbol': 'KOTAKNIFTY', 'company_name': 'Kotak Nifty ETF'},
 {'symbol': 'MAFANG', 'company_name': 'Mirae Asset FANG+ ETF'},
 {'symbol': 'MASPTOP50', 'company_name': 'Mirae Asset S&P 500 Top 50 ETF'},
 {'symbol': 'MON100', 'company_name': 'Motilal Oswal Nasdaq 100 ETF'},
 {'symbol': 'ITBEES', 'company_name': 'Nippon India ETF Nifty IT BeES'}]

NSE_SME_FALLBACK = [{'symbol': 'GIRIRAJ', 'company_name': 'Giriraj Civil Developers Limited'},
 {'symbol': 'RAJPUTANA', 'company_name': 'Rajputana Biodiesel Limited'},
 {'symbol': 'CRAYONS', 'company_name': 'Crayons Advertising Limited'}]

NSE_REITS = [{'symbol': 'EMBASSY', 'company_name': 'Embassy Office Parks REIT'},
 {'symbol': 'MINDSPACE', 'company_name': 'Mindspace Business Parks REIT'},
 {'symbol': 'BROOKFIELD', 'company_name': 'Brookfield India Real Estate Trust REIT'},
 {'symbol': 'NEXUSMALLS', 'company_name': 'Nexus Select Trust REIT'}]

NSE_INVITS = [{'symbol': 'INDIGRID', 'company_name': 'India Grid Trust InvIT'},
 {'symbol': 'POWERGRID', 'company_name': 'PowerGrid Infrastructure InvIT'},
 {'symbol': 'NHAI', 'company_name': 'National Highways Infra Trust InvIT'},
 {'symbol': 'ATINVIT', 'company_name': 'Atria Convergence InvIT'},
 {'symbol': 'IRHFL', 'company_name': 'IRB InvIT Fund'}]
